apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qoq0a2bo2-java-quarkus
  janus-idp.io/tekton: qoq0a2bo2-java-quarkus
  backstage.io/kubernetes-id: qoq0a2bo2-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qoq0a2bo2-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
